"""Adicionado Usuario e Relacionamentos

Revision ID: 2f17fed17dd9
Revises: 65527b54cfa3
Create Date: 2021-08-09 06:25:34.934293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f17fed17dd9'
down_revision = '65527b54cfa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user', type_='foreignkey')

    # ### end Alembic commands ###
