"""Nova coluna tamanhos

Revision ID: 65527b54cfa3
Revises: 0732ef72cd30
Create Date: 2021-08-08 16:11:17.029840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65527b54cfa3'
down_revision = '0732ef72cd30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('sizes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'sizes')
    # ### end Alembic commands ###
