"""Adicionando Pedido

Revision ID: 94d0df257665
Revises: 2f17fed17dd9
Create Date: 2021-08-22 12:14:30.724824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d0df257665'
down_revision = '2f17fed17dd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qtt', sa.Integer(), nullable=True),
    sa.Column('delivery_place', sa.String(), nullable=True),
    sa.Column('delivery_type', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='fk_deal_product'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_deal_user'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_id'))

    op.drop_table('deal')
    # ### end Alembic commands ###
